//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudydeskDesktopApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://localhost:44304/WebServiceGetTutors.asmx")]
        public string StudydeskDesktopApp_GetTutors_WebServiceGetTutors {
            get {
                return ((string)(this["StudydeskDesktopApp_GetTutors_WebServiceGetTutors"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://localhost:44304/WebServiceAuthentication.asmx")]
        public string StudydeskDesktopApp_Authentication_WebServiceAuthentication {
            get {
                return ((string)(this["StudydeskDesktopApp_Authentication_WebServiceAuthentication"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://localhost:44304/WebServiceGetTutorById.asmx")]
        public string StudydeskDesktopApp_GetTutorById_WebServiceGetTutorById {
            get {
                return ((string)(this["StudydeskDesktopApp_GetTutorById_WebServiceGetTutorById"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://localhost:44304/WebServicePostTutor.asmx")]
        public string StudydeskDesktopApp_PostTutor_WebServicePostTutor {
            get {
                return ((string)(this["StudydeskDesktopApp_PostTutor_WebServicePostTutor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://localhost:44304/WebServicePostStudent.asmx")]
        public string StudydeskDesktopApp_PostStudent_WebServicePostStudent {
            get {
                return ((string)(this["StudydeskDesktopApp_PostStudent_WebServicePostStudent"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://localhost:44304/WebServiceUpdateTutor.asmx")]
        public string StudydeskDesktopApp_PutTutors_WebServiceUpdateTutor {
            get {
                return ((string)(this["StudydeskDesktopApp_PutTutors_WebServiceUpdateTutor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://localhost:44304/WebServiceGetStudentById.asmx")]
        public string StudydeskDesktopApp_GetStudentById_WebServiceGetStudentById {
            get {
                return ((string)(this["StudydeskDesktopApp_GetStudentById_WebServiceGetStudentById"]));
            }
        }
    }
}
