//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace StudydeskDesktopApp.Authenticate {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServiceAuthenticationSoap", Namespace="http://tempuri.org/")]
    public partial class WebServiceAuthentication : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AutenticarUsuarioTutorOperationCompleted;
        
        private System.Threading.SendOrPostCallback AutenticarUsuarioEstudianteOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebServiceAuthentication() {
            this.Url = global::StudydeskDesktopApp.Properties.Settings.Default.StudydeskDesktopApp_Authenticate_WebServiceAuthentication;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AutenticarUsuarioTutorCompletedEventHandler AutenticarUsuarioTutorCompleted;
        
        /// <remarks/>
        public event AutenticarUsuarioEstudianteCompletedEventHandler AutenticarUsuarioEstudianteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AutenticarUsuarioTutor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResponseService AutenticarUsuarioTutor(string email, string password) {
            object[] results = this.Invoke("AutenticarUsuarioTutor", new object[] {
                        email,
                        password});
            return ((ResponseService)(results[0]));
        }
        
        /// <remarks/>
        public void AutenticarUsuarioTutorAsync(string email, string password) {
            this.AutenticarUsuarioTutorAsync(email, password, null);
        }
        
        /// <remarks/>
        public void AutenticarUsuarioTutorAsync(string email, string password, object userState) {
            if ((this.AutenticarUsuarioTutorOperationCompleted == null)) {
                this.AutenticarUsuarioTutorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAutenticarUsuarioTutorOperationCompleted);
            }
            this.InvokeAsync("AutenticarUsuarioTutor", new object[] {
                        email,
                        password}, this.AutenticarUsuarioTutorOperationCompleted, userState);
        }
        
        private void OnAutenticarUsuarioTutorOperationCompleted(object arg) {
            if ((this.AutenticarUsuarioTutorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AutenticarUsuarioTutorCompleted(this, new AutenticarUsuarioTutorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AutenticarUsuarioEstudiante", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResponseService AutenticarUsuarioEstudiante(string email, string password) {
            object[] results = this.Invoke("AutenticarUsuarioEstudiante", new object[] {
                        email,
                        password});
            return ((ResponseService)(results[0]));
        }
        
        /// <remarks/>
        public void AutenticarUsuarioEstudianteAsync(string email, string password) {
            this.AutenticarUsuarioEstudianteAsync(email, password, null);
        }
        
        /// <remarks/>
        public void AutenticarUsuarioEstudianteAsync(string email, string password, object userState) {
            if ((this.AutenticarUsuarioEstudianteOperationCompleted == null)) {
                this.AutenticarUsuarioEstudianteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAutenticarUsuarioEstudianteOperationCompleted);
            }
            this.InvokeAsync("AutenticarUsuarioEstudiante", new object[] {
                        email,
                        password}, this.AutenticarUsuarioEstudianteOperationCompleted, userState);
        }
        
        private void OnAutenticarUsuarioEstudianteOperationCompleted(object arg) {
            if ((this.AutenticarUsuarioEstudianteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AutenticarUsuarioEstudianteCompleted(this, new AutenticarUsuarioEstudianteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ResponseService {
        
        private string statusField;
        
        private string messageField;
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void AutenticarUsuarioTutorCompletedEventHandler(object sender, AutenticarUsuarioTutorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AutenticarUsuarioTutorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AutenticarUsuarioTutorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponseService Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseService)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void AutenticarUsuarioEstudianteCompletedEventHandler(object sender, AutenticarUsuarioEstudianteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AutenticarUsuarioEstudianteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AutenticarUsuarioEstudianteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponseService Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseService)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591